from pathlib import Path

main_path = Path(r'D:\Codex\MTNsim\src\mtnsim\gui\main_window.py')
main = main_path.read_text(encoding='utf-8')
old_connect = """        self.scene_3d_view.open_result_summary_requested.connect(self.open_current_result_summary_file)\n        self.scene_3d_view.export_snapshot_requested.connect(self.export_current_3d_snapshot)\n        self.scene_3d_view.export_markdown_requested.connect(self.export_current_3d_markdown)\n"""
new_connect = """        self.scene_3d_view.open_result_summary_requested.connect(self.open_current_result_summary_file)\n        self.scene_3d_view.export_snapshot_requested.connect(self.export_current_3d_snapshot)\n        self.scene_3d_view.export_snapshot_hires_requested.connect(self.export_current_3d_snapshot_hires)\n        self.scene_3d_view.export_markdown_requested.connect(self.export_current_3d_markdown)\n"""
if old_connect in main:
    main = main.replace(old_connect, new_connect, 1)

start = main.index("    def export_current_3d_snapshot(self) -> None:\n")
end = main.index("    def export_current_3d_markdown(self) -> None:\n")
replacement = """    def export_current_3d_snapshot(self) -> None:\n        frame = self.scene_3d_view.canvas.frame_data\n        if frame is None:\n            QMessageBox.information(self, '3D Export', 'Open a 3D scene or result before exporting a snapshot.')\n            return\n        base_dir = Path(self.current_result_summary.output_dir) if self.current_result_summary is not None else Path.cwd()\n        stem = self.current_result_summary.run.scenario if self.current_result_summary is not None else 'scene3d'\n        default_path = base_dir / f'{stem}_3d_snapshot.png'\n        file_path, _ = QFileDialog.getSaveFileName(self, 'Save 3D Snapshot', str(default_path), 'PNG Files (*.png)')\n        if not file_path:\n            return\n        output_path = self._export_current_3d_snapshot_to(Path(file_path), scale_factor=1.0)\n        QMessageBox.information(self, '3D Export', '3D snapshot saved to:\n' + str(output_path))\n\n    def export_current_3d_snapshot_hires(self) -> None:\n        frame = self.scene_3d_view.canvas.frame_data\n        if frame is None:\n            QMessageBox.information(self, '3D Export', 'Open a 3D scene or result before exporting a hi-res snapshot.')\n            return\n        base_dir = Path(self.current_result_summary.output_dir) if self.current_result_summary is not None else Path.cwd()\n        stem = self.current_result_summary.run.scenario if self.current_result_summary is not None else 'scene3d'\n        default_path = base_dir / f'{stem}_3d_snapshot_2x.png'\n        file_path, _ = QFileDialog.getSaveFileName(self, 'Save Hi-Res 3D Snapshot', str(default_path), 'PNG Files (*.png)')\n        if not file_path:\n            return\n        output_path = self._export_current_3d_snapshot_to(Path(file_path), scale_factor=2.0)\n        QMessageBox.information(self, '3D Export', 'Hi-res 3D snapshot saved to:\n' + str(output_path))\n\n    def _export_current_3d_snapshot_to(self, output_path: Path, scale_factor: float = 1.0) -> Path:\n        pixmap = self.scene_3d_view.canvas.grab()\n        image = pixmap.toImage()\n        if scale_factor > 1.0:\n            image = image.scaled(max(1, int(image.width() * scale_factor)), max(1, int(image.height() * scale_factor)), Qt.KeepAspectRatio, Qt.SmoothTransformation)\n        output_path.parent.mkdir(parents=True, exist_ok=True)\n        image.save(str(output_path), 'PNG')\n        suffix = ' (hi-res)' if scale_factor > 1.0 else ''\n        self._append_log(f'[info] Exported 3D snapshot{suffix}: {output_path}')\n        self.statusBar().showMessage(f'Exported 3D snapshot{suffix}: {output_path.name}')\n        return output_path\n\n"""
main = main[:start] + replacement + main[end:]
main_path.write_text(main, encoding='utf-8')
